services:
  db:
    image: postgres:18-alpine3.23
    container_name: python-backend-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass98
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/

volumes:
  pgdata:
